### ISSUE TITLE
Add support for localized tags (Summary(fr)) and tags with qualifiers (Requires(post))

### ISSUE THREAD

**Issue by xsuchy** [packit/specfile#120]
I have very simple script:
```
#!/usr/bin/python3                                                                                             
from specfile import Specfile
import sys

# this is dump, but do the work
filename = sys.argv[1]
specfile = Specfile(filename)

with specfile.sections() as sections:
    print(sections.changelog)
```

And when I run it as `/print-spec-changelog.py rpm-specs/algobox.spec` it traceback with:

```
Traceback (most recent call last):
  File "/home/msuchy/projects/license-validate/./print-spec-changelog.py", line 9, in <module>
    with specfile.sections() as sections:
  File "/usr/lib64/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/specfile.py", line 135, in sections
    sections = Sections.parse(lines)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/sections.py", line 199, in parse
    data.append(Section(lines[start][1:], lines[start + 1 : end]))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/sections.py", line 64, in __init__
    raise ValueError(f"Invalid section name: '{name}'")
ValueError: Invalid section name: 'description(fr)'
```

It seems that this lines is causing the problem. https://src.fedoraproject.org/rpms/algobox/blob/rawhide/f/algobox.spec#_25
Nevertheless, this line is a valid one.

**Comment by nforro** [comment]
Thanks for the report, this is definitely a bug.

**Comment by nforro** [comment]
> Nevertheless, this line is a valid one.

Actually, it isn't. Parsing only works because it is assumed to be a part of `%description` section:

```bash
$ rpm -qp --qf %{description} algobox-1.0.3-6.fc38.src.rpm 
Algobox is an initiation to algorithmic software at high school level.

%description(fr)
Algobox est un logiciel d'initiation à l'algorithmique au niveau lycée.
```

The correct way to specify language for description is to use `%description -l fr`.

So, this is the same case as in #126. Strictly speaking it's not valid, but we should be able to parse such a spec file anyway.
