### ISSUE TITLE
Unable to open rpm-specs/coreutils-provides.inc: No such file or directory

### ISSUE THREAD

**Issue by xsuchy** [packit/specfile#121]
I have very simple script:

```
#!/usr/bin/python3                                                                                             
from specfile import Specfile
import sys

# this is dumb, but do the work
filename = sys.argv[1]
specfile = Specfile(filename)

with specfile.sections() as sections:
    print(sections.changelog)

```
And when I run it as `./print-spec-changelog.py rpm-specs/coreutils.spec` I get:

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/specfile/rpm.py", line 319, in parse
    spec = rpm.spec(tmp.name, rpm.RPMSPEC_ANYARCH | rpm.RPMSPEC_FORCE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: can't parse specfile


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/msuchy/projects/license-validate/./print-spec-changelog.py", line 7, in <module>
    specfile = Specfile(filename)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/specfile.py", line 48, in __init__
    self._spec = RPM.parse(str(self), self.sourcedir, self.macros)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/rpm.py", line 326, in parse
    raise RPMException(stderr=stderr) from e
specfile.exceptions.RPMException: Unable to open rpm-specs/coreutils-provides.inc: No such file or directory
```

The culprit is https://src.fedoraproject.org/rpms/coreutils/blob/rawhide/f/coreutils.spec#_13
Not sure who and why is trying to load the source file.

**Comment by xsuchy** [comment]
Very similar situation can be observed with rpm-specs/bitcoin-core.spec rpm-specs/efivar.spec rpm-specs/efibootmgr.spec 

The file rpm-specs/gdb.spec has problem with patch:
```
Traceback (most recent call last):
  File "/home/msuchy/projects/license-validate/./print-spec-changelog.py", line 7, in <module>
    specfile = Specfile(filename)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/specfile.py", line 48, in __init__
    self._spec = RPM.parse(str(self), self.sourcedir, self.macros)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/rpm.py", line 326, in parse
    raise RPMException(stderr=stderr) from e
specfile.exceptions.RPMException: Unable to open rpm-specs/_gdb.spec.Patch.include: No such file or directory
rpm-specs/gdb.spec
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/specfile/rpm.py", line 319, in parse
    spec = rpm.spec(tmp.name, rpm.RPMSPEC_ANYARCH | rpm.RPMSPEC_FORCE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: can't parse specfile
```

The file rpm-specs/gdesklets-goodweather.spec has slightly different error:
```
Traceback (most recent call last):
  File "/home/msuchy/projects/license-validate/./print-spec-changelog.py", line 7, in <module>
    specfile = Specfile(filename)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/specfile.py", line 48, in __init__
    self._spec = RPM.parse(str(self), self.sourcedir, self.macros)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/rpm.py", line 326, in parse
    raise RPMException(stderr=stderr) from e
specfile.exceptions.RPMException: attempt to use unversioned python, define %__python to /usr/bin/python2 or /usr/bin/python3 explicitly
```
But the TB from spec file is almost identical.

**Comment by nforro** [comment]
The tracebacks are almost identical because RPM fails to parse the spec files, but the reasons for the failures are different.

In the first two cases it's missing include files, they exist in dist-git and they have to be present while parsing.

The last spec file is unparseable as it is (you can try with `rpmspec -P gdesklets-goodweather.spec`), but you can overcome that with:

```python
specfile = Specfile(filename, macros=[('__python', '/usr/bin/python3')])
```

**Comment by xsuchy** [comment]
I am parsing files from https://src.fedoraproject.org/lookaside/rpm-specs-latest.tar.xz if we have to be in dist-git during parsing, then we should state it in the documentation. But it would be better if we did not need to be there.

> specfile = Specfile(filename, macros=[('__python', '/usr/bin/python3')])

We need to find a general solution. E.g., loading all macros from `/usr/lib/rpm/macros.d/*`

**Comment by xsuchy** [comment]
I can imagine something like:
```
from specfile import Macros

macros = Macros()  # with an optional argument containing a list of directories where macros are stored
specfile = Specfile(filename, macros=macros)
```

**Comment by nforro** [comment]
> We need to find a general solution. E.g., loading all macros from `/usr/lib/rpm/macros.d/*`

That's already being done (by RPM), and that's the reason for the failure, in Fedora (not sure since what release), `%__python` is defined as `%error`, on purpose.

**Comment by xsuchy** [comment]
Hmm in the second case https://src.fedoraproject.org/rpms/gdesklets-goodweather/blob/rawhide/f/gdesklets-goodweather.spec#_38 it is incorrectly commented macro. Should be fixed by proposing change to spec file. Done https://src.fedoraproject.org/rpms/gdesklets-goodweather/pull-request/1

Lets only focus on loading patches and sources in this issue.

**Comment by xsuchy** [comment]
I can confirm that executing the script in dist-git returns correct data:
```
cd /tmp
fedpkg clone -a coreutils
print-spec-changelog.py /tmp/coreutils/coreutils.spec
```
This works correctly. 
But the need to do the full checkout of dist-git is really inconvenient.

**Comment by xsuchy** [comment]
Looking at why the files are needed...

It is because of:
```
Source51:   coreutils-provides.inc
...
Provides: coreutils-full = %{version}-%{release}
%include %{SOURCE51}
```

Hmm but the error happens on line 319 https://github.com/packit/specfile/blob/main/specfile/rpm.py#L319 but just a few lines down https://github.com/packit/specfile/blob/main/specfile/rpm.py#L321 you are trying to use dummy sources. So can we catch the exception and continue parsing with dummy sources?

**Comment by nforro** [comment]
I'll have a look. I'm not sure if a dummy source can be used in this case, but maybe it can.

**Comment by xsuchy** [comment]
If I would like to build the package, then ... yes.

It has no impact if I want to parse changelog. Alter Version and Release. Which is what we do most of the time.

**Comment by nforro** [comment]
Next steps:

- **optionally** enable faking *included sources* (create empty file for every non-existing source)
- show warnings when this happens
- set `tainted` attribute to indicate `Specfile` represents potentially incomplete spec
