### ISSUE TITLE
specfile.exceptions.RPMException: line 40: %package -n python3-gssapi: package python3-gssapi already exists

### ISSUE THREAD

**Issue by xsuchy** [packit/specfile#125]
With the package (from epel7 branch) https://src.fedoraproject.org/rpms/python3-gssapi/blob/epel7/f/python3-gssapi.spec I get:
```
Traceback (most recent call last):
  File "/home/msuchy/projects/license-validate/./print-spec-changelog.py", line 7, in <module>
    specfile = Specfile(filename)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/specfile.py", line 48, in __init__
    self._spec = RPM.parse(str(self), self.sourcedir, self.macros)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/rpm.py", line 326, in parse
    raise RPMException(stderr=stderr) from e
specfile.exceptions.RPMException: line 40: %package -n python3-gssapi: package python3-gssapi already exists
```

**Comment by nforro** [comment]
That's because on Fedora `%python3_pkgversion` expands to `3`, but on EL 7 it expands to `36`, so the subpackage name is `python36-gssapi`, which is valid (not duplicate).
