### ISSUE TITLE
Illegal char ')' (0x29) in: Obsoletes: rubygem(boxgrinder-build-ebs-delivery-plugin) < 0.0.4-2

### ISSUE THREAD

**Issue by xsuchy** [packit/specfile#127]
In the file https://src.fedoraproject.org/rpms/rubygem-boxgrinder-build/blob/rawhide/f/rubygem-boxgrinder-build.spec
I get:
```
Traceback (most recent call last):
  File "/home/msuchy/projects/license-validate/./print-spec-changelog.py", line 7, in <module>
    specfile = Specfile(filename)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/specfile.py", line 48, in __init__
    self._spec = RPM.parse(str(self), self.sourcedir, self.macros)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/rpm.py", line 326, in parse
    raise RPMException(stderr=stderr) from e
specfile.exceptions.RPMException: line 72: Illegal char ')' (0x29) in: Obsoletes: rubygem(boxgrinder-build-ebs-delivery-plugin) < 0.0.4-2
```

**Comment by xsuchy** [comment]
Similar situation is in sssd.spec:
```
specfile.exceptions.RPMException: line 311: Illegal char '?' (0xffffff8d) in: Requires: samba-client-libs >= balíček samba-devel není nainstalován
```

**Comment by nforro** [comment]
This is another case of locale issue, it doesn't happen with `en_US` or `C`.

**Comment by nforro** [comment]
Related to #124.

**Comment by nforro** [comment]
> This is another case of locale issue, it doesn't happen with `en_US` or `C`.

Correction, this applies only to `sssd.spec`. Disregarding the locale, `rubygem-boxgrinder-build.spec` is invalid and unparseable, because `Obsoletes` requires an explicit package name.
