### ISSUE TITLE
Invalid version (epoch must be unsigned integer)

### ISSUE THREAD

**Issue by xsuchy** [packit/specfile#171]
When parsing `jpegxl.spec` from Fedora I get:

<details>
<summary>specfile.exceptions.RPMException: line 85: Invalid version (epoch must be unsigned integer): %{epoch}:0.7.0-1.fc37: Recommends:     jxl-pixbuf-loader = %{epoch}:0.7.0-1.fc37
</summary>
<pre>
Traceback (most recent call last):
  File "/home/msuchy/projects/license-validate/./print-spec-changelog.py", line 7, in <module>
    specfile = Specfile(filename, force_parse=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/specfile.py", line 57, in __init__
    self._parser.parse(str(self))
  File "/usr/lib/python3.11/site-packages/specfile/spec_parser.py", line 303, in parse
    self.spec, self.tainted = self._do_parse(content, extra_macros)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/spec_parser.py", line 239, in _do_parse
    spec = get_rpm_spec(content, rpm.RPMSPEC_ANYARCH | rpm.RPMSPEC_FORCE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/spec_parser.py", line 176, in get_rpm_spec
    raise RPMException(stderr=stderr) from e
specfile.exceptions.RPMException: attempt to use unversioned python, define %__python to /usr/bin/python2 or /usr/bin/python3 explicitly
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/specfile/spec_parser.py", line 174, in get_rpm_spec
    return rpm.spec(tmp.name, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: can't parse specfile

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/msuchy/projects/license-validate/./print-spec-changelog.py", line 7, in <module>
    specfile = Specfile(filename, force_parse=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/specfile.py", line 57, in __init__
    self._parser.parse(str(self))
  File "/usr/lib/python3.11/site-packages/specfile/spec_parser.py", line 303, in parse
    self.spec, self.tainted = self._do_parse(content, extra_macros)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/spec_parser.py", line 239, in _do_parse
    spec = get_rpm_spec(content, rpm.RPMSPEC_ANYARCH | rpm.RPMSPEC_FORCE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/spec_parser.py", line 176, in get_rpm_spec
    raise RPMException(stderr=stderr) from e
specfile.exceptions.RPMException: line 85: Invalid version (epoch must be unsigned integer): %{epoch}:0.7.0-1.fc37: Recommends:     jxl-pixbuf-loader = %{epoch}:0.7.0-1.fc37
</pre>
</details>

That is because it contains the line:

```
Recommends:     jxl-pixbuf-loader = %{epoch}:%{version}-%{release}
```

$ rpm -q python3-specfile
python3-specfile-0.11.0-1.fc37.noarch

**Comment by nforro** [comment]
This is not a specfile issue, the spec file is invalid. The `Epoch` tag was removed in the [latest commit](https://src.fedoraproject.org/rpms/jpegxl/c/b907c00f322960c2b4ab1d135ccde50684d14bb9?branch=rawhide) in rawhide branch and that made the spec file unparseable.

**Comment by xsuchy** [comment]
Ah, thank you. Reported as https://src.fedoraproject.org/rpms/jpegxl/pull-request/1
