### ISSUE TITLE
Implement parsing of conditions

### ISSUE THREAD

**Issue by nforro** [packit/specfile#231]
Statements such as `%if`, `%else` and `%endif` are currently treated as regular section content.
That can cause issues, especially with conditions spanning across multiple sections - if a section is deleted, modified or moved, it can lead to syntax errors as the condition block could be broken apart.
Figure out how to deal with this.

**Comment by lachmanfrantisek** [comment]
Still relevant. Let us know if you need this (either in Specfile or for Packit).

**Comment by xsuchy** [comment]
I am hitting this when parsing amavis.spec. I get this TB
```
Traceback (most recent call last):
  File "/home/msuchy/projects/license-validate/./convert-spec-universal.py", line 65, in <module>
    with specfile.tags(section) as tags:
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/msuchy/.local/lib/python3.12/site-packages/specfile/context_management.py", line 133, in __call__
    self.values[key] = next(self.generators[key])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/msuchy/.local/lib/python3.12/site-packages/specfile/specfile.py", line 292, in tags
    tags = Tags.parse(section, context=self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/msuchy/.local/lib/python3.12/site-packages/specfile/tags.py", line 497, in parse
    lines = process_conditions(list(section), macro_definitions, context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/msuchy/.local/lib/python3.12/site-packages/specfile/conditions.py", line 133, in process_conditions
    result.append((line, branches[-2]))
                         ~~~~~~~~^^^^
IndexError: list index out of range
```

**Comment by xsuchy** [comment]
Parsing of `pg_auto_failover.spec` from Fedora is hitting this issue as well. :(

**Comment by xsuchy** [comment]
Parsing of python3.14 is affected by this too.

**Comment by xsuchy** [comment]
This is complete list of packages from Fedora affected by this issue:
```
amavis.spec
autoconf.spec
dogtag-pki.spec
frysk.spec
gdb.spec
gnutls.spec
grub2.spec
libpst.spec
make.spec
mariadb10.11.spec
mariadb11.8.spec
mysql8.0.spec
mysql8.4.spec
nasm.spec
pg_auto_failover.spec
php-pecl-apcu.spec
postgresql16-anonymizer.spec
postgresql16-decoderbufs.spec
postgresql16-pgaudit.spec
postgresql16-pg_cron.spec
postgresql16-pg_repack.spec
postgresql16-pg_tle.spec
postgresql16-pgvector.spec
postgresql16-postgis.spec
postgresql16.spec
postgresql17-postgis.spec
postgresql17.spec
postgresql18-decoderbufs.spec
postgresql18-pgaudit.spec
postgresql18-pg_repack.spec
postgresql18-pgvector.spec
postgresql18-postgis.spec
postgresql18.spec
python3.10.spec
python3.11.spec
python3.12.spec
python3.13.spec
python3.14.spec
python3.9.spec
rsyslog.spec
uim.spec
usermode.spec
xorgxrdp.spec
```
