### ISSUE TITLE
Cannot parse "%setup -q -n %(tar ft %SOURCE0|head -n1|sed s,/,,)"

### ISSUE THREAD

**Issue by xsuchy** [packit/specfile#233]
### What happened? What is the problem?

During parsing dl_poly.spec I get

```
  File "/usr/lib/python3.11/site-packages/specfile/spec_parser.py", line 201, in get_rpm_spec
    return rpm.spec(tmp.name, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: can't parse specfile


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/msuchy/projects/specfile/tests/test-parsing/./parse.py", line 8, in <module>
    specfile = Specfile(filename, force_parse=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/specfile.py", line 71, in __init__
    self._parser.parse(str(self))
  File "/usr/lib/python3.11/site-packages/specfile/spec_parser.py", line 353, in parse
    self.spec, self.tainted = self._do_parse(content, extra_macros)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/spec_parser.py", line 318, in _do_parse
    return get_rpm_spec(content, rpm.RPMSPEC_ANYARCH), tainted
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/spec_parser.py", line 203, in get_rpm_spec
    raise RPMException(stderr=stderr) from e
specfile.exceptions.RPMException: line 106: Bad %setup option -n: missing argument
```

The specific line in that spec file is:

```
%setup -q -n %(tar ft %SOURCE0|head -n1|sed s,/,,)
```

### Workaround

- [ ] There is an existing workaround that can be used until this issue is fixed.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by nforro** [comment]
Thanks, this is certainly a bug.

**Comment by nforro** [comment]
This could be solved by creating a dummy source that would be a complete compressed tar archive containing a top-level directory rather than just a file header to fool rpm file type detection. However, I'm not sure it's worth doing for a single package.

**Comment by nforro** [comment]
To be consistent it would make sense to do this for all supported (by rpm) archive types, but that would bring a substantial amount of additional dependencies.

**Comment by xsuchy** [comment]
I think this does not need to be a fatal error. The warning will be enough. I am querying the preamble. I can live with partial parsing.

**Comment by nforro** [comment]
Still relevant.
