### ISSUE TITLE
New option to validae rpm SPEC in RHEL build environment

### ISSUE THREAD

**Issue by cathay4t** [packit/specfile#345]
### What happened? What is the problem?

When running packit for CentOS Stream 9, the `Specfile` complains about:

```
2024-01-18 17:27:28.729 utils.py          ERROR  The -V flag for cargo_prep is not supported in Fedora
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/specfile/spec_parser.py", line 226, in get_rpm_spec
    return rpm.spec(tmp.name, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: can't parse specfile


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/packit/cli/utils.py", line 47, in covered_func
    func(config=config, *args, **kwargs)  # noqa: B026
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/packit/cli/utils.py", line 143, in covered_func
    func(*args, **decorated_func_kwargs)
  File "/usr/lib/python3.11/site-packages/packit/cli/propose_downstream.py", line 232, in pull_from_upstream
    sync_release(
  File "/usr/lib/python3.11/site-packages/packit/cli/propose_downstream.py", line 75, in sync_release
    api.sync_release(
  File "/usr/lib/python3.11/site-packages/packit/api.py", line 961, in sync_release
    self.up.set_specfile(self.dg.specfile)
                         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/packit/base_git.py", line 119, in specfile
    self._specfile = Specfile(
                     ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/specfile.py", line 75, in __init__
    self._parser.parse(str(self))
  File "/usr/lib/python3.11/site-packages/specfile/spec_parser.py", line 380, in parse
    self.spec, self.tainted = self._do_parse(content, extra_macros)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/spec_parser.py", line 294, in _do_parse
    spec = get_rpm_spec(content, rpm.RPMSPEC_ANYARCH | rpm.RPMSPEC_FORCE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/specfile/spec_parser.py", line 228, in get_rpm_spec
    raise RPMException(stderr=stderr) from e
specfile.exceptions.RPMException: The -V flag for cargo_prep is not supported in Fedora
2024-01-18 17:27:28.730 local_project.py  DEBUG  Cleaning: /tmp/tmps0v3hoxf
```

The RPM SPEC line is:

```
%cargo_prep -V 3
```

which is valid in RHEL/CentOS build macros

### What did you expect to happen?

The `Specfile` class could provide a option to validate RHEL/CentOS rpm specs

### Steps to reproduce

```bash
1. centpkg clone nmstate
2. Create `~/packit_ds_nmstate.yml` with:


---
downstream_package_name: nmstate
upstream_project_url: https://github.com/nmstate/nmstate
issue_repository: https://github.com/nmstate/nmstate
update_release: false
upstream_package_name: nmstate
upstream_tag_template: v{version}
copy_upstream_release_description: true

packages:
  nmstate-centos:
    pkg_tool: centpkg
    specfile_path: packaging/nmstate.spec

jobs:
  - job: pull_from_upstream
    trigger: release
    packages: [nmstate-centos]
    dist_git_branches:
      - c9s


3. inside `nmstate` folder created by `centpkg`, invoke `packit -d --config ~/packit_ds_nmstate.yml pull-from-upstream`
```

### Workaround

- [ ] There is an existing workaround that can be used until this issue is fixed.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by nforro** [comment]
The important thing here is, you are running this on Fedora with Fedora macros, so this is expected to happen. It's not possible to mitigate it with any option, you would have to redefine the macro in question (and possibly many others) with a compatible implementation, or run in a c9s chroot/container.
